[colors.bright]
black = "0x000000"
blue = "0x0d62ac"
cyan = "0x25a0a6"
green = "0x4fa637"
magenta = "0x7218a6"
red = "0xb63625"
white = "0xffffff"
yellow = "0xc1b72c"

[colors.normal]
black = "0x000000"
blue = "0x0d62ac"
cyan = "0x25a0a6"
green = "0x4fa637"
magenta = "0x7218a6"
red = "0xb63625"
white = "0xffffff"
yellow = "0xc1b72c"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
