[colors.bright]
black = "0x000000"
blue = "0x3d7aff"
cyan = "0x17c4f8"
green = "0x0be879"
magenta = "0xab35f4"
red = "0xf11356"
white = "0xffffff"
yellow = "0xf3f305"

[colors.normal]
black = "0x000000"
blue = "0x3d7aff"
cyan = "0x17c4f8"
green = "0x0be879"
magenta = "0xab35f4"
red = "0xf11356"
white = "0xffffff"
yellow = "0xf3f305"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
